### ISSUE TITLE
Cannot run the default version of Amundsen because `amundsenmetadata` container exits

### ISSUE THREAD

**Issue by ivanfeliciano** [stemma-ai/amundsen-custom#12]
Hi, I am following the steps from the standard Amundsen installation explained in the README file. However, it aborts and shows the following error

```
amundsenmetadata    | Traceback (most recent call last):
amundsenmetadata    |   File "/usr/local/bin/gunicorn", line 8, in <module>
amundsenmetadata    |     sys.exit(run())
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
amundsenmetadata    |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 231, in run
amundsenmetadata    |     super().run()
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
amundsenmetadata    |     Arbiter(self).run()
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 58, in __init__
amundsenmetadata    |     self.setup(app)
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 118, in setup
amundsenmetadata    |     self.app.wsgi()
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
amundsenmetadata    |     self.callable = self.load()
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
amundsenmetadata    |     return self.load_wsgiapp()
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
amundsenmetadata    |     return util.import_app(self.app_uri)
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
amundsenmetadata    |     mod = importlib.import_module(module)
amundsenmetadata    |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
amundsenmetadata    |     return _bootstrap._gcd_import(name[level:], package, level)
amundsenmetadata    |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
amundsenmetadata    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
amundsenmetadata    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
amundsenmetadata    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
amundsenmetadata    |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
amundsenmetadata    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
amundsenmetadata    |   File "/usr/local/amundsen/metadata/wsgi.py", line 1, in <module>
amundsenmetadata    |     from metadata_service import create_app
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/metadata_service/__init__.py", line 17, in <module>
amundsenmetadata    |     from metadata_service.api.badge import BadgeAPI
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/metadata_service/api/__init__.py", line 10, in <module>
amundsenmetadata    |     from metadata_service.proxy import BaseProxy
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/metadata_service/proxy/__init__.py", line 10, in <module>
amundsenmetadata    |     from metadata_service.proxy.base_proxy import BaseProxy
amundsenmetadata    |   File "/usr/local/lib/python3.7/site-packages/metadata_service/proxy/base_proxy.py", line 11, in <module>
amundsenmetadata    |     from amundsen_common.models.query import Query
amundsenmetadata    | ModuleNotFoundError: No module named 'amundsen_common.models.query'
amundsenmetadata exited with code 1
Aborting on container exit...
Stopping amundsenfrontend ... done
Stopping amundsensearch   ... done
Stopping neo4j_amundsen   ... done
Stopping es_amundsen      ... done
ERROR: 1
```

**Comment by simonezambonim** [comment]
I have the same problem here! Did you figure it out @ivanfeliciano ?

**Comment by ivanfeliciano** [comment]
No @simonezambonim , I did not. I decided to move to the original amundsen repo https://github.com/amundsen-io/amundsen

**Comment by zacr** [comment]
I had the exact same issue. I ended up using a much more recent tag on the amundsen monorepo (dacf29672b). Also because of updates in the monorepo I added two COPY statements in each Dockerfile to make sure all the various requirements files are there for pip. 

COPY amundsen/requirements-common.txt /usr/local/amundsen/metadata/
COPY amundsen/requirements-dev.txt /usr/local/amundsen/metadata/

This directory structure seems to be working now.
