### ISSUE TITLE
Dockerfile.frontend won't build

### ISSUE THREAD

**Issue by delwaterman** [stemma-ai/amundsen-custom#15]
Using a direct fork of the repo, with no changes made, it looks like the Dockerfile.frontend is missing the common requirements file.

```bash
 => ERROR [stage-1 6/8] RUN pip install upstream/ &&     pip install -r requirements.txt                                                                                                                                                                 1.9s
------
 > [stage-1 6/8] RUN pip install upstream/ &&     pip install -r requirements.txt:
#19 1.312 Processing ./upstream
#19 1.312   DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
#19 1.312    pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
#19 1.657     ERROR: Command errored out with exit status 1:
#19 1.657      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-reqlphnj/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-reqlphnj/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qtuomjkl
#19 1.657          cwd: /tmp/pip-req-build-reqlphnj/
#19 1.657     Complete output (14 lines):
#19 1.657     /bin/sh: 1: npm: not found
#19 1.657     ERROR:root:npm must be available
#19 1.657     /bin/sh: 1: npm: not found
#19 1.657     /tmp/pip-req-build-reqlphnj/setup.py:30: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
#19 1.657       logging.warn('Installation of npm dependencies failed')
#19 1.657     WARNING:root:Installation of npm dependencies failed
#19 1.657     /tmp/pip-req-build-reqlphnj/setup.py:31: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
#19 1.657       logging.warn(str(e))
#19 1.657     WARNING:root:Command '['npm install']' returned non-zero exit status 127.
#19 1.657     Traceback (most recent call last):
#19 1.657       File "<string>", line 1, in <module>
#19 1.657       File "/tmp/pip-req-build-reqlphnj/setup.py", line 41, in <module>
#19 1.657         with open(requirements_path) as requirements_file:
#19 1.657     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-reqlphnj/requirements-common.txt'
#19 1.657     ----------------------------------------
#19 1.657 WARNING: Discarding file:///usr/local/amundsen/frontend/upstream. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#19 1.657 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bramelfrink** [comment]
@delwaterman I'm a bit late to the party, but I've found a way to resolve this.
I assume that at the time of creating the amundsen-custom project, the Amundsen project was not yet using symlinks for the requirement files.
As Docker is not handling the symlinks, you need to update `Dockerfile.frontend` to also include the following lines before the `pip install` part:
```
# Resolve symlink
COPY amundsen/requirements.txt /usr/local/amundsen/frontend/upstream
COPY amundsen/requirements-common.txt /usr/local/amundsen/frontend/upstream
COPY amundsen/requirements-dev.txt /usr/local/amundsen/frontend/upstream
```

I hope this helps!
